"""ComputeMesh protocol reference types."""

from .control import ControlEnvelope, ProtocolFault, StructuredError, parse_control_envelope
from .message_contracts import MessageContractError, MessageContractValidator
from .node_identity import (
    AUTH_METHOD,
    Ed25519ChallengeVerifier,
    NodeAuthProof,
    NodeIdentityError,
    NodeProofMalformed,
    VerificationKey,
    VerificationKeyResolver,
    create_node_auth_proof,
    key_id_from_public_key,
    signing_message,
)
from .node_session import (
    AuthenticationAttempt,
    AuthenticationDecision,
    AuthenticationExpired,
    AuthenticationFailed,
    AuthenticationVerifier,
    CapabilityMismatch,
    NodeHelloInfo,
    NodeSession,
    NodeSessionError,
    NodeSessionState,
    ProfileMismatch,
    ProtocolVersionMismatch,
    SessionSnapshot,
    SessionTransitionError,
)
from .session_contracts import (
    SessionMessageContractError,
    SessionMessageContractValidator,
)
from .session_wire import (
    BenchmarkAcceptanceDecision,
    BenchmarkAcceptancePolicy,
    BenchmarkRejected,
    NodeSessionWireError,
    NodeSessionWireHandler,
    SessionActorMismatch,
    SessionMessageBindingError,
    SessionMessageIdempotencyConflict,
    SessionProtocolMismatch,
    SessionRevisionMismatch,
    UnsupportedSessionMessage,
)

__all__ = [
    "ControlEnvelope",
    "ProtocolFault",
    "StructuredError",
    "parse_control_envelope",
    "MessageContractError",
    "MessageContractValidator",
    "AUTH_METHOD",
    "Ed25519ChallengeVerifier",
    "NodeAuthProof",
    "NodeIdentityError",
    "NodeProofMalformed",
    "VerificationKey",
    "VerificationKeyResolver",
    "create_node_auth_proof",
    "key_id_from_public_key",
    "signing_message",
    "AuthenticationAttempt",
    "AuthenticationDecision",
    "AuthenticationExpired",
    "AuthenticationFailed",
    "AuthenticationVerifier",
    "CapabilityMismatch",
    "NodeHelloInfo",
    "NodeSession",
    "NodeSessionError",
    "NodeSessionState",
    "ProfileMismatch",
    "ProtocolVersionMismatch",
    "SessionSnapshot",
    "SessionTransitionError",
    "SessionMessageContractError",
    "SessionMessageContractValidator",
    "BenchmarkAcceptanceDecision",
    "BenchmarkAcceptancePolicy",
    "BenchmarkRejected",
    "NodeSessionWireError",
    "NodeSessionWireHandler",
    "SessionActorMismatch",
    "SessionMessageBindingError",
    "SessionMessageIdempotencyConflict",
    "SessionProtocolMismatch",
    "SessionRevisionMismatch",
    "UnsupportedSessionMessage",
]
