"""ComputeMesh protocol reference types."""

from .control import ControlEnvelope, ProtocolFault, StructuredError, parse_control_envelope
from .message_contracts import MessageContractError, MessageContractValidator
from .node_session import (
    AuthenticationAttempt,
    AuthenticationDecision,
    AuthenticationExpired,
    AuthenticationFailed,
    AuthenticationVerifier,
    CapabilityMismatch,
    NodeHelloInfo,
    NodeSession,
    NodeSessionError,
    NodeSessionState,
    ProfileMismatch,
    ProtocolVersionMismatch,
    SessionSnapshot,
    SessionTransitionError,
)
from .session_contracts import (
    SessionMessageContractError,
    SessionMessageContractValidator,
)
from .session_wire import (
    BenchmarkAcceptanceDecision,
    BenchmarkAcceptancePolicy,
    BenchmarkRejected,
    NodeSessionWireError,
    NodeSessionWireHandler,
    SessionActorMismatch,
    SessionMessageBindingError,
    SessionMessageIdempotencyConflict,
    SessionProtocolMismatch,
    SessionRevisionMismatch,
    UnsupportedSessionMessage,
)

__all__ = [
    "ControlEnvelope",
    "ProtocolFault",
    "StructuredError",
    "parse_control_envelope",
    "MessageContractError",
    "MessageContractValidator",
    "AuthenticationAttempt",
    "AuthenticationDecision",
    "AuthenticationExpired",
    "AuthenticationFailed",
    "AuthenticationVerifier",
    "CapabilityMismatch",
    "NodeHelloInfo",
    "NodeSession",
    "NodeSessionError",
    "NodeSessionState",
    "ProfileMismatch",
    "ProtocolVersionMismatch",
    "SessionSnapshot",
    "SessionTransitionError",
    "SessionMessageContractError",
    "SessionMessageContractValidator",
    "BenchmarkAcceptanceDecision",
    "BenchmarkAcceptancePolicy",
    "BenchmarkRejected",
    "NodeSessionWireError",
    "NodeSessionWireHandler",
    "SessionActorMismatch",
    "SessionMessageBindingError",
    "SessionMessageIdempotencyConflict",
    "SessionProtocolMismatch",
    "SessionRevisionMismatch",
    "UnsupportedSessionMessage",
]
